data_path: '/content/drive/MyDrive/VASA-1-master/video'
checkpoint_path: '/content/drive/MyDrive/VASA-1-master/checkpoints'
log_path: '/content/drive/MyDrive/VASA-1-master/train_base.log'
epochs: 10
batch_size: 8
lr: 0.0001
log_interval: 10
checkpoint_interval: 5
resume: False
